"""Diagnosis questions and goals constants.

This module contains all the predefined questions and goals for the v2 diagnosis system.
Questions are managed as constants rather than being dynamically generated by AI.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Domain(str, Enum):
    """Available engineering domains."""

    FRONTEND = "frontend"
    BACKEND = "backend"
    INFRASTRUCTURE = "infrastructure"

    @property
    def display_name(self) -> str:
        """Get display name for the domain."""
        names = {
            Domain.FRONTEND: "フロントエンド",
            Domain.BACKEND: "バックエンド",
            Domain.INFRASTRUCTURE: "インフラ",
        }
        return names.get(self, self.value)

    @property
    def description(self) -> str:
        """Get description for the domain."""
        descriptions = {
            Domain.FRONTEND: "ユーザーインターフェースの開発。React、Vue、TypeScriptなど",
            Domain.BACKEND: "サーバーサイド開発。API設計、データベース、認証など",
            Domain.INFRASTRUCTURE: "クラウド・インフラ構築。AWS、Docker、CI/CDなど",
        }
        return descriptions.get(self, "")


# Domain list for API responses
DOMAINS = [
    {
        "id": Domain.FRONTEND.value,
        "label": Domain.FRONTEND.display_name,
        "description": Domain.FRONTEND.description,
    },
    {
        "id": Domain.BACKEND.value,
        "label": Domain.BACKEND.display_name,
        "description": Domain.BACKEND.description,
    },
    {
        "id": Domain.INFRASTRUCTURE.value,
        "label": Domain.INFRASTRUCTURE.display_name,
        "description": Domain.INFRASTRUCTURE.description,
    },
]


@dataclass
class QuestionOption:
    """A single option for a question."""

    id: str
    label: str
    value: int = 0  # Optional score/weight for the option


@dataclass
class Question:
    """A structured question with options."""

    id: str
    text: str
    type: str  # "single" or "multiple"
    category: str  # Question category for grouping
    options: list[QuestionOption] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "id": self.id,
            "text": self.text,
            "type": self.type,
            "category": self.category,
            "options": [{"id": opt.id, "label": opt.label} for opt in self.options],
        }


@dataclass
class Goal:
    """A predefined goal for a domain."""

    id: str
    label: str
    description: str
    domain: Domain

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "id": self.id,
            "label": self.label,
            "description": self.description,
        }


# =============================================================================
# GOALS - Predefined goals for each domain
# =============================================================================

GOALS: dict[str, list[Goal]] = {
    Domain.FRONTEND.value: [
        Goal(
            id="fe_junior",
            label="ジュニアフロントエンドエンジニアを目指す",
            description="基礎から学び、フロントエンド開発の実務スキルを身につける",
            domain=Domain.FRONTEND,
        ),
        Goal(
            id="fe_middle",
            label="ミドルフロントエンドエンジニアを目指す",
            description="実務経験を活かし、より高度な設計・実装力を習得",
            domain=Domain.FRONTEND,
        ),
        Goal(
            id="fe_senior",
            label="シニアフロントエンドエンジニアを目指す",
            description="技術リードやアーキテクトとして活躍できるスキルを習得",
            domain=Domain.FRONTEND,
        ),
        Goal(
            id="fe_fullstack",
            label="フルスタック化（フロントエンド軸）",
            description="フロントエンドを強みにしつつバックエンドも扱えるように",
            domain=Domain.FRONTEND,
        ),
    ],
    Domain.BACKEND.value: [
        Goal(
            id="be_junior",
            label="ジュニアバックエンドエンジニアを目指す",
            description="基礎から学び、バックエンド開発の実務スキルを身につける",
            domain=Domain.BACKEND,
        ),
        Goal(
            id="be_middle",
            label="ミドルバックエンドエンジニアを目指す",
            description="実務経験を活かし、より高度な設計・実装力を習得",
            domain=Domain.BACKEND,
        ),
        Goal(
            id="be_senior",
            label="シニアバックエンドエンジニアを目指す",
            description="大規模システムの設計・運用ができるスキルを習得",
            domain=Domain.BACKEND,
        ),
        Goal(
            id="be_architect",
            label="システムアーキテクトを目指す",
            description="マイクロサービス設計やシステム全体の設計力を強化",
            domain=Domain.BACKEND,
        ),
    ],
    Domain.INFRASTRUCTURE.value: [
        Goal(
            id="infra_junior",
            label="ジュニアインフラエンジニアを目指す",
            description="基礎から学び、インフラ構築・運用の実務スキルを身につける",
            domain=Domain.INFRASTRUCTURE,
        ),
        Goal(
            id="infra_middle",
            label="ミドルインフラエンジニアを目指す",
            description="実務経験を活かし、より高度なインフラ設計力を習得",
            domain=Domain.INFRASTRUCTURE,
        ),
        Goal(
            id="infra_sre",
            label="SREエンジニアを目指す",
            description="サービスの信頼性向上と運用自動化のスキルを習得",
            domain=Domain.INFRASTRUCTURE,
        ),
        Goal(
            id="infra_devops",
            label="DevOpsエンジニアを目指す",
            description="CI/CD構築や開発プロセス改善のスキルを習得",
            domain=Domain.INFRASTRUCTURE,
        ),
    ],
}


# =============================================================================
# COMMON QUESTIONS - Questions for all domains
# =============================================================================

COMMON_QUESTIONS: list[Question] = [
    Question(
        id="exp_years",
        text="エンジニアとしての経験年数を教えてください",
        type="single",
        category="基本情報",
        options=[
            QuestionOption(id="exp_0", label="未経験（これから学習開始）", value=0),
            QuestionOption(id="exp_1", label="1年未満", value=1),
            QuestionOption(id="exp_1_3", label="1〜3年", value=2),
            QuestionOption(id="exp_3_5", label="3〜5年", value=3),
            QuestionOption(id="exp_5_plus", label="5年以上", value=4),
        ],
    ),
    Question(
        id="learning_hours",
        text="週にどれくらいの学習時間を確保できますか？",
        type="single",
        category="基本情報",
        options=[
            QuestionOption(id="hours_5", label="5時間未満", value=5),
            QuestionOption(id="hours_10", label="5〜10時間", value=10),
            QuestionOption(id="hours_20", label="10〜20時間", value=20),
            QuestionOption(id="hours_20_plus", label="20時間以上", value=30),
        ],
    ),
    Question(
        id="learning_style",
        text="好みの学習スタイルを教えてください",
        type="single",
        category="学習スタイル",
        options=[
            QuestionOption(id="style_video", label="動画教材（Udemy、YouTubeなど）"),
            QuestionOption(id="style_book", label="書籍・ドキュメント"),
            QuestionOption(id="style_hands_on", label="ハンズオン・実践プロジェクト"),
            QuestionOption(id="style_interactive", label="インタラクティブ教材（Progate等）"),
        ],
    ),
    Question(
        id="programming_basics",
        text="プログラミングの基礎知識について当てはまるものを選んでください",
        type="single",
        category="基礎スキル",
        options=[
            QuestionOption(id="basics_none", label="プログラミング未経験", value=0),
            QuestionOption(id="basics_learning", label="基礎文法を学習中", value=1),
            QuestionOption(id="basics_simple", label="簡単なプログラムが書ける", value=2),
            QuestionOption(id="basics_practical", label="実務で使用経験あり", value=3),
            QuestionOption(id="basics_advanced", label="複雑な処理も実装できる", value=4),
        ],
    ),
    Question(
        id="git_experience",
        text="Git/バージョン管理の経験について教えてください",
        type="single",
        category="基礎スキル",
        options=[
            QuestionOption(id="git_none", label="使ったことがない", value=0),
            QuestionOption(id="git_basic", label="基本操作（commit、push）ができる", value=1),
            QuestionOption(id="git_branch", label="ブランチ運用ができる", value=2),
            QuestionOption(id="git_team", label="チーム開発で使用経験あり", value=3),
            QuestionOption(
                id="git_advanced", label="高度な操作（rebase、squash等）もできる", value=4
            ),
        ],
    ),
    Question(
        id="english_skill",
        text="英語のドキュメントを読む能力について教えてください",
        type="single",
        category="学習スタイル",
        options=[
            QuestionOption(id="eng_none", label="ほぼ読めない"),
            QuestionOption(id="eng_translate", label="翻訳ツールを使えば理解できる"),
            QuestionOption(id="eng_slow", label="時間をかければ読める"),
            QuestionOption(id="eng_fluent", label="問題なく読める"),
        ],
    ),
]


# =============================================================================
# DOMAIN-SPECIFIC QUESTIONS
# =============================================================================

DOMAIN_QUESTIONS: dict[str, list[Question]] = {
    # =========================================================================
    # FRONTEND QUESTIONS
    # =========================================================================
    Domain.FRONTEND.value: [
        Question(
            id="fe_html_css",
            text="HTML/CSSのスキルレベルを教えてください",
            type="single",
            category="基礎技術",
            options=[
                QuestionOption(id="fe_html_none", label="ほとんど経験がない", value=0),
                QuestionOption(id="fe_html_basic", label="基本的なページが作れる", value=1),
                QuestionOption(
                    id="fe_html_responsive", label="レスポンシブデザインが実装できる", value=2
                ),
                QuestionOption(
                    id="fe_html_advanced",
                    label="複雑なレイアウトやアニメーションも実装できる",
                    value=3,
                ),
            ],
        ),
        Question(
            id="fe_javascript",
            text="JavaScriptの経験レベルを教えてください",
            type="single",
            category="言語",
            options=[
                QuestionOption(id="fe_js_none", label="ほとんど経験がない", value=0),
                QuestionOption(id="fe_js_basic", label="基本文法は理解している", value=1),
                QuestionOption(id="fe_js_dom", label="DOM操作やイベント処理ができる", value=2),
                QuestionOption(
                    id="fe_js_async",
                    label="非同期処理（Promise、async/await）も理解している",
                    value=3,
                ),
                QuestionOption(
                    id="fe_js_advanced", label="ES6+の機能を活用した開発ができる", value=4
                ),
            ],
        ),
        Question(
            id="fe_typescript",
            text="TypeScriptの経験について教えてください",
            type="single",
            category="言語",
            options=[
                QuestionOption(id="fe_ts_none", label="使ったことがない", value=0),
                QuestionOption(id="fe_ts_learning", label="学習中", value=1),
                QuestionOption(id="fe_ts_basic", label="基本的な型定義ができる", value=2),
                QuestionOption(id="fe_ts_advanced", label="Genericsや高度な型も使える", value=3),
            ],
        ),
        Question(
            id="fe_framework",
            text="使用経験のあるフロントエンドフレームワークを選んでください",
            type="multiple",
            category="フレームワーク",
            options=[
                QuestionOption(id="fe_fw_none", label="経験なし"),
                QuestionOption(id="fe_fw_react", label="React"),
                QuestionOption(id="fe_fw_vue", label="Vue.js"),
                QuestionOption(id="fe_fw_angular", label="Angular"),
                QuestionOption(id="fe_fw_next", label="Next.js"),
                QuestionOption(id="fe_fw_nuxt", label="Nuxt.js"),
                QuestionOption(id="fe_fw_svelte", label="Svelte"),
            ],
        ),
        Question(
            id="fe_framework_level",
            text="最も得意なフレームワークの習熟度を教えてください",
            type="single",
            category="フレームワーク",
            options=[
                QuestionOption(id="fe_fw_lvl_none", label="フレームワーク未経験", value=0),
                QuestionOption(id="fe_fw_lvl_tutorial", label="チュートリアルレベル", value=1),
                QuestionOption(id="fe_fw_lvl_simple", label="簡単なアプリが作れる", value=2),
                QuestionOption(id="fe_fw_lvl_practical", label="実務で使用経験あり", value=3),
                QuestionOption(
                    id="fe_fw_lvl_advanced", label="アーキテクチャ設計もできる", value=4
                ),
            ],
        ),
        Question(
            id="fe_state_management",
            text="状態管理について経験のあるものを選んでください",
            type="multiple",
            category="状態管理",
            options=[
                QuestionOption(id="fe_state_none", label="状態管理ライブラリ未経験"),
                QuestionOption(id="fe_state_redux", label="Redux"),
                QuestionOption(id="fe_state_zustand", label="Zustand"),
                QuestionOption(id="fe_state_recoil", label="Recoil"),
                QuestionOption(id="fe_state_pinia", label="Pinia (Vue)"),
                QuestionOption(id="fe_state_vuex", label="Vuex"),
            ],
        ),
        Question(
            id="fe_testing",
            text="フロントエンドテストの経験について教えてください",
            type="multiple",
            category="テスト",
            options=[
                QuestionOption(id="fe_test_none", label="テスト経験なし"),
                QuestionOption(id="fe_test_unit", label="ユニットテスト（Jest等）"),
                QuestionOption(
                    id="fe_test_component", label="コンポーネントテスト（Testing Library等）"
                ),
                QuestionOption(id="fe_test_e2e", label="E2Eテスト（Cypress、Playwright等）"),
            ],
        ),
        Question(
            id="fe_build_tools",
            text="ビルドツール/パッケージマネージャの経験を教えてください",
            type="multiple",
            category="ツール",
            options=[
                QuestionOption(id="fe_tool_npm", label="npm"),
                QuestionOption(id="fe_tool_yarn", label="Yarn"),
                QuestionOption(id="fe_tool_pnpm", label="pnpm"),
                QuestionOption(id="fe_tool_webpack", label="Webpack"),
                QuestionOption(id="fe_tool_vite", label="Vite"),
                QuestionOption(id="fe_tool_none", label="特になし"),
            ],
        ),
    ],
    # =========================================================================
    # BACKEND QUESTIONS
    # =========================================================================
    Domain.BACKEND.value: [
        Question(
            id="be_language",
            text="バックエンド開発で使用経験のある言語を選んでください",
            type="multiple",
            category="言語",
            options=[
                QuestionOption(id="be_lang_none", label="バックエンド言語未経験"),
                QuestionOption(id="be_lang_python", label="Python"),
                QuestionOption(id="be_lang_java", label="Java"),
                QuestionOption(id="be_lang_go", label="Go"),
                QuestionOption(id="be_lang_node", label="Node.js (JavaScript/TypeScript)"),
                QuestionOption(id="be_lang_ruby", label="Ruby"),
                QuestionOption(id="be_lang_php", label="PHP"),
                QuestionOption(id="be_lang_csharp", label="C#"),
                QuestionOption(id="be_lang_rust", label="Rust"),
            ],
        ),
        Question(
            id="be_language_level",
            text="最も得意なバックエンド言語の習熟度を教えてください",
            type="single",
            category="言語",
            options=[
                QuestionOption(id="be_lang_lvl_none", label="バックエンド言語未経験", value=0),
                QuestionOption(id="be_lang_lvl_basic", label="基本文法は理解している", value=1),
                QuestionOption(id="be_lang_lvl_simple", label="簡単なAPIが作れる", value=2),
                QuestionOption(id="be_lang_lvl_practical", label="実務で使用経験あり", value=3),
                QuestionOption(
                    id="be_lang_lvl_advanced", label="パフォーマンス最適化もできる", value=4
                ),
            ],
        ),
        Question(
            id="be_framework",
            text="使用経験のあるバックエンドフレームワークを選んでください",
            type="multiple",
            category="フレームワーク",
            options=[
                QuestionOption(id="be_fw_none", label="フレームワーク未経験"),
                QuestionOption(id="be_fw_fastapi", label="FastAPI"),
                QuestionOption(id="be_fw_django", label="Django"),
                QuestionOption(id="be_fw_flask", label="Flask"),
                QuestionOption(id="be_fw_spring", label="Spring Boot"),
                QuestionOption(id="be_fw_express", label="Express.js"),
                QuestionOption(id="be_fw_nestjs", label="NestJS"),
                QuestionOption(id="be_fw_rails", label="Ruby on Rails"),
                QuestionOption(id="be_fw_laravel", label="Laravel"),
                QuestionOption(id="be_fw_gin", label="Gin (Go)"),
            ],
        ),
        Question(
            id="be_database",
            text="データベースの経験について教えてください",
            type="multiple",
            category="データベース",
            options=[
                QuestionOption(id="be_db_none", label="データベース未経験"),
                QuestionOption(id="be_db_mysql", label="MySQL"),
                QuestionOption(id="be_db_postgresql", label="PostgreSQL"),
                QuestionOption(id="be_db_mongodb", label="MongoDB"),
                QuestionOption(id="be_db_redis", label="Redis"),
                QuestionOption(id="be_db_dynamodb", label="DynamoDB"),
                QuestionOption(id="be_db_oracle", label="Oracle"),
            ],
        ),
        Question(
            id="be_database_level",
            text="データベース設計・操作のスキルレベルを教えてください",
            type="single",
            category="データベース",
            options=[
                QuestionOption(id="be_db_lvl_none", label="ほとんど経験がない", value=0),
                QuestionOption(id="be_db_lvl_basic", label="基本的なCRUD操作ができる", value=1),
                QuestionOption(id="be_db_lvl_join", label="JOINやサブクエリも使える", value=2),
                QuestionOption(id="be_db_lvl_design", label="テーブル設計ができる", value=3),
                QuestionOption(
                    id="be_db_lvl_advanced", label="パフォーマンスチューニングもできる", value=4
                ),
            ],
        ),
        Question(
            id="be_api_design",
            text="API設計の経験について教えてください",
            type="single",
            category="API設計",
            options=[
                QuestionOption(id="be_api_none", label="API設計の経験なし", value=0),
                QuestionOption(
                    id="be_api_basic", label="簡単なREST APIを作成したことがある", value=1
                ),
                QuestionOption(id="be_api_restful", label="RESTful設計原則を理解している", value=2),
                QuestionOption(
                    id="be_api_practical", label="実務でAPI設計を担当したことがある", value=3
                ),
                QuestionOption(id="be_api_advanced", label="GraphQL、gRPCなども経験あり", value=4),
            ],
        ),
        Question(
            id="be_auth",
            text="認証・認可の実装経験について教えてください",
            type="multiple",
            category="セキュリティ",
            options=[
                QuestionOption(id="be_auth_none", label="認証実装の経験なし"),
                QuestionOption(id="be_auth_session", label="セッション認証"),
                QuestionOption(id="be_auth_jwt", label="JWT認証"),
                QuestionOption(id="be_auth_oauth", label="OAuth 2.0"),
                QuestionOption(id="be_auth_oidc", label="OpenID Connect"),
            ],
        ),
        Question(
            id="be_testing",
            text="バックエンドテストの経験について教えてください",
            type="multiple",
            category="テスト",
            options=[
                QuestionOption(id="be_test_none", label="テスト経験なし"),
                QuestionOption(id="be_test_unit", label="ユニットテスト"),
                QuestionOption(id="be_test_integration", label="統合テスト"),
                QuestionOption(id="be_test_api", label="APIテスト"),
                QuestionOption(id="be_test_load", label="負荷テスト"),
            ],
        ),
        Question(
            id="be_architecture",
            text="アーキテクチャパターンの理解度を教えてください",
            type="single",
            category="アーキテクチャ",
            options=[
                QuestionOption(id="be_arch_none", label="特に意識したことがない", value=0),
                QuestionOption(id="be_arch_mvc", label="MVCパターンは理解している", value=1),
                QuestionOption(
                    id="be_arch_layered", label="レイヤードアーキテクチャを適用できる", value=2
                ),
                QuestionOption(
                    id="be_arch_ddd", label="クリーンアーキテクチャ/DDDの経験あり", value=3
                ),
                QuestionOption(
                    id="be_arch_microservices", label="マイクロサービス設計もできる", value=4
                ),
            ],
        ),
    ],
    # =========================================================================
    # INFRASTRUCTURE QUESTIONS
    # =========================================================================
    Domain.INFRASTRUCTURE.value: [
        Question(
            id="infra_cloud",
            text="使用経験のあるクラウドプラットフォームを選んでください",
            type="multiple",
            category="クラウド",
            options=[
                QuestionOption(id="infra_cloud_none", label="クラウド未経験"),
                QuestionOption(id="infra_cloud_aws", label="AWS"),
                QuestionOption(id="infra_cloud_gcp", label="Google Cloud"),
                QuestionOption(id="infra_cloud_azure", label="Azure"),
                QuestionOption(id="infra_cloud_other", label="その他（Heroku、Vercel等）"),
            ],
        ),
        Question(
            id="infra_cloud_level",
            text="クラウドサービスの習熟度を教えてください",
            type="single",
            category="クラウド",
            options=[
                QuestionOption(id="infra_cloud_lvl_none", label="ほとんど経験がない", value=0),
                QuestionOption(
                    id="infra_cloud_lvl_basic",
                    label="基本的なサービス（EC2、S3等）を使える",
                    value=1,
                ),
                QuestionOption(
                    id="infra_cloud_lvl_practical", label="実務でクラウド構築の経験あり", value=2
                ),
                QuestionOption(
                    id="infra_cloud_lvl_design", label="アーキテクチャ設計ができる", value=3
                ),
                QuestionOption(
                    id="infra_cloud_lvl_advanced",
                    label="マルチリージョン・高可用性設計もできる",
                    value=4,
                ),
            ],
        ),
        Question(
            id="infra_aws_services",
            text="使用経験のあるAWSサービスを選んでください（AWS経験者のみ）",
            type="multiple",
            category="AWS",
            options=[
                QuestionOption(id="infra_aws_ec2", label="EC2"),
                QuestionOption(id="infra_aws_s3", label="S3"),
                QuestionOption(id="infra_aws_rds", label="RDS"),
                QuestionOption(id="infra_aws_lambda", label="Lambda"),
                QuestionOption(id="infra_aws_ecs", label="ECS/EKS"),
                QuestionOption(id="infra_aws_cloudfront", label="CloudFront"),
                QuestionOption(id="infra_aws_vpc", label="VPC"),
                QuestionOption(id="infra_aws_iam", label="IAM"),
                QuestionOption(id="infra_aws_none", label="AWSは未使用"),
            ],
        ),
        Question(
            id="infra_container",
            text="コンテナ技術の経験について教えてください",
            type="single",
            category="コンテナ",
            options=[
                QuestionOption(id="infra_container_none", label="コンテナ未経験", value=0),
                QuestionOption(
                    id="infra_container_docker_basic", label="Dockerの基本操作ができる", value=1
                ),
                QuestionOption(
                    id="infra_container_docker_compose",
                    label="Docker Composeで複数コンテナ管理ができる",
                    value=2,
                ),
                QuestionOption(
                    id="infra_container_k8s_basic", label="Kubernetesの基本を理解している", value=3
                ),
                QuestionOption(
                    id="infra_container_k8s_advanced", label="K8sクラスタの運用経験あり", value=4
                ),
            ],
        ),
        Question(
            id="infra_iac",
            text="Infrastructure as Code (IaC) の経験について教えてください",
            type="multiple",
            category="IaC",
            options=[
                QuestionOption(id="infra_iac_none", label="IaC未経験"),
                QuestionOption(id="infra_iac_terraform", label="Terraform"),
                QuestionOption(id="infra_iac_cloudformation", label="CloudFormation"),
                QuestionOption(id="infra_iac_pulumi", label="Pulumi"),
                QuestionOption(id="infra_iac_ansible", label="Ansible"),
                QuestionOption(id="infra_iac_cdk", label="AWS CDK"),
            ],
        ),
        Question(
            id="infra_cicd",
            text="CI/CDの経験について教えてください",
            type="multiple",
            category="CI/CD",
            options=[
                QuestionOption(id="infra_cicd_none", label="CI/CD未経験"),
                QuestionOption(id="infra_cicd_github_actions", label="GitHub Actions"),
                QuestionOption(id="infra_cicd_gitlab", label="GitLab CI"),
                QuestionOption(id="infra_cicd_jenkins", label="Jenkins"),
                QuestionOption(id="infra_cicd_circleci", label="CircleCI"),
                QuestionOption(id="infra_cicd_argocd", label="ArgoCD"),
            ],
        ),
        Question(
            id="infra_cicd_level",
            text="CI/CDパイプラインの構築スキルを教えてください",
            type="single",
            category="CI/CD",
            options=[
                QuestionOption(id="infra_cicd_lvl_none", label="構築経験なし", value=0),
                QuestionOption(
                    id="infra_cicd_lvl_basic", label="簡単なパイプラインを構築できる", value=1
                ),
                QuestionOption(
                    id="infra_cicd_lvl_practical", label="テスト・デプロイを自動化できる", value=2
                ),
                QuestionOption(
                    id="infra_cicd_lvl_advanced", label="複雑なワークフロー設計もできる", value=3
                ),
            ],
        ),
        Question(
            id="infra_monitoring",
            text="監視・ログ管理の経験について教えてください",
            type="multiple",
            category="監視",
            options=[
                QuestionOption(id="infra_mon_none", label="監視ツール未経験"),
                QuestionOption(id="infra_mon_cloudwatch", label="CloudWatch"),
                QuestionOption(id="infra_mon_datadog", label="Datadog"),
                QuestionOption(id="infra_mon_prometheus", label="Prometheus/Grafana"),
                QuestionOption(id="infra_mon_elk", label="ELK Stack"),
                QuestionOption(id="infra_mon_newrelic", label="New Relic"),
            ],
        ),
        Question(
            id="infra_linux",
            text="Linuxの操作スキルを教えてください",
            type="single",
            category="OS",
            options=[
                QuestionOption(id="infra_linux_none", label="Linuxほぼ未経験", value=0),
                QuestionOption(id="infra_linux_basic", label="基本的なコマンドが使える", value=1),
                QuestionOption(id="infra_linux_shell", label="シェルスクリプトが書ける", value=2),
                QuestionOption(id="infra_linux_admin", label="サーバー管理ができる", value=3),
                QuestionOption(
                    id="infra_linux_advanced", label="パフォーマンスチューニングもできる", value=4
                ),
            ],
        ),
    ],
}


def get_goals_for_domain(domain: str) -> list[Goal]:
    """Get goals for a specific domain."""
    return GOALS.get(domain, [])


def get_domain_questions(domain: str) -> list[Question]:
    """Get domain-specific questions."""
    return DOMAIN_QUESTIONS.get(domain, [])
